# BetterOcean: static web shell + serverless API (Gradient AI in background).
# Set GRADIENT_AGENT_ENDPOINT and GRADIENT_AGENT_KEY on the "api" component in App Platform.
name: betterocean
region: nyc

ingress:
  rules:
    - match:
        path:
          prefix: /api
      component:
        name: api
    - match:
        path:
          prefix: /
      component:
        name: web

static_sites:
  - name: web
    environment_slug: html
    source_dir: /
    index_document: index.html
    github:
      branch: main
      deploy_on_push: true
      repo: stalkiq/betterocean

functions:
  - name: api
    source_dir: api
    github:
      branch: main
      deploy_on_push: true
      repo: stalkiq/betterocean
    routes:
      - path: /api
        preserve_path_prefix: true
