# BetterOcean: static web shell + API service (Gradient AI in background).
# Set GRADIENT_AGENT_ENDPOINT and GRADIENT_AGENT_KEY on the "api" service in App Platform.
name: betterocean
region: nyc

ingress:
  rules:
    - match:
        path:
          prefix: /api
      component:
        name: api
    - match:
        path:
          prefix: /
      component:
        name: web

static_sites:
  - name: web
    environment_slug: html
    source_dir: /
    index_document: index.html
    github:
      branch: main
      deploy_on_push: true
      repo: stalkiq/betterocean

services:
  - name: api
    source_dir: api-service
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    run_command: npm start
    github:
      branch: main
      deploy_on_push: true
      repo: stalkiq/betterocean
    envs:
      - key: GRADIENT_AGENT_ENDPOINT
        scope: RUN_AND_BUILD_TIME
        type: GENERAL
        value: "https://inference.do-ai.run/v1"
      - key: GRADIENT_AGENT_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: "sk-do-4AWFoeMqCUXGWDFGj7wv28690WpGCcWeZTM2_HR1vViLlYBo_BLyo8apjf"
